# Generated by Django 5.2.8 on 2025-11-24 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alkatreszcsoport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alkcsop', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Beszallito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beszallito', models.CharField(max_length=50)),
                ('lezart', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mertekegyseg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mertegys', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rendszam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendszam', models.CharField(max_length=20)),
                ('tulajdonos', models.CharField(max_length=50)),
                ('lezart', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Alkatresz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cikkszam', models.CharField(max_length=100, unique=True)),
                ('leiras', models.CharField(max_length=50)),
                ('info', models.CharField(blank=True, max_length=300, null=True)),
                ('keszlet', models.FloatField(default=0)),
                ('listaar', models.IntegerField()),
                ('alkatreszcsoport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alkatreszek', to='raktar.alkatreszcsoport')),
                ('mertekegyseg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alkatreszek', to='raktar.mertekegyseg')),
            ],
        ),
        migrations.CreateModel(
            name='Bizonylat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gebizid', models.CharField(max_length=20)),
                ('bizonylattipus', models.BooleanField()),
                ('szamlaszam', models.CharField(blank=True, max_length=50, null=True)),
                ('szallitolevelszam', models.CharField(blank=True, max_length=50, null=True)),
                ('datum', models.DateField()),
                ('lezart', models.BooleanField(default=False)),
                ('szallito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bizonylatok', to='raktar.beszallito')),
                ('rendszam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bizonylatok', to='raktar.rendszam')),
            ],
        ),
        migrations.CreateModel(
            name='Bizonylatsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mennyiseg', models.FloatField()),
                ('aktualisar', models.IntegerField()),
                ('alkatresz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bizonylatsorok', to='raktar.alkatresz', to_field='cikkszam')),
                ('bizonylat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorok', to='raktar.bizonylat')),
            ],
            options={
                'unique_together': {('bizonylat', 'alkatresz')},
            },
        ),
    ]
