# Generated by Django 5.2.8 on 2025-11-30 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raktar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bizonylat',
            old_name='gebizid',
            new_name='genbizid',
        ),
    ]
