# Generated by Django 5.2.8 on 2025-12-01 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raktar', '0002_rename_gebizid_bizonylat_genbizid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bizonylat',
            name='rendszam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bizonylatok', to='raktar.rendszam'),
        ),
        migrations.AlterField(
            model_name='bizonylat',
            name='szallito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bizonylatok', to='raktar.beszallito'),
        ),
    ]
