# Generated by Django 5.2 on 2026-01-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raktar', '0003_alter_bizonylat_rendszam_alter_bizonylat_szallito'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlapAdat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ev', models.CharField(max_length=10)),
                ('maxBizId', models.IntegerField(default=0)),
            ],
        ),
    ]
