# Generated by Django 5.2 on 2026-01-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raktar', '0004_alapadat'),
    ]

    operations = [
        migrations.AddField(
            model_name='alapadat',
            name='szorzo',
            field=models.FloatField(default=1.1),
        ),
    ]
