# Generated by Django 5.2 on 2026-01-05 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raktar', '0005_alapadat_szorzo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bizonylat',
            name='rendszam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bizonylatok', to='raktar.rendszam'),
        ),
        migrations.AlterField(
            model_name='bizonylat',
            name='szallito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bizonylatok', to='raktar.beszallito'),
        ),
        migrations.AlterField(
            model_name='bizonylatsor',
            name='alkatresz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bizonylatsorok', to='raktar.alkatresz', to_field='cikkszam'),
        ),
        migrations.AlterField(
            model_name='bizonylatsor',
            name='bizonylat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sorok', to='raktar.bizonylat'),
        ),
    ]
